### ISSUE TITLE
Add UI button

### ISSUE THREAD

**Issue by OBWANDO** [OBWANDO/azplay#33]
- [x] Create UI button in C++ #30
- [x] Create unit tests for UI button #31
- [ ] Write compile harness #32
