### ISSUE TITLE
Here's an Epic to hold the work for the feature I told you about

### ISSUE THREAD

**Issue by forhalle** [OBWANDO/azplay#48]
**List the story-point level tasks needed to deliver this feature:
- [ ] Make this change to the UI #45
- [ ] Make this change to the API #46
- [ ] The asset processor also needs to change #47

**List any related work, and describe the relationship (relates to, duplicates, is blocked by, blocks, is duplicated by, duplicates, etc.)**
- [ ] Here is a bigger roadmap-worthy request #44 (relates to)

**Please describe the acceptance criteria**
The criteria when work is considered complete.
